services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  
  Brightside\Pagelist\DataProcessing\PaginatedPagelistDatabaseQueryProcessor:
    public: true
  Brightside\Pagelist\DataProcessing\SelectedPagesDatabaseQueryProcessor:
    public: true